-- ============================================================
-- KARTHICK CRACKERS - FULL SQL SERVER DATABASE DEPLOYMENT SCRIPT
-- Target: SQL Server 2016+ / Azure SQL Database / MonsterASP / SmarterASP
-- ============================================================

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = N'KarthickCrackersDb')
BEGIN
    CREATE DATABASE [KarthickCrackersDb];
END
GO

USE [KarthickCrackersDb];
GO

-- 1. CATEGORIES TABLE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Categories]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[Categories] (
        [CategoryId] INT IDENTITY(1,1) NOT NULL,
        [CategoryName] NVARCHAR(100) NOT NULL,
        [Description] NVARCHAR(MAX) NULL,
        [IsActive] BIT NOT NULL DEFAULT 1,
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [ModifiedDate] DATETIME2 NULL,
        CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED ([CategoryId] ASC)
    );
END
GO

-- 2. PRODUCTS TABLE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Products]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[Products] (
        [ProductId] INT IDENTITY(1,1) NOT NULL,
        [ProductCode] NVARCHAR(50) NOT NULL,
        [ProductName] NVARCHAR(200) NOT NULL,
        [CategoryId] INT NOT NULL,
        [Price] DECIMAL(18,2) NOT NULL,
        [MRPPrice] DECIMAL(18,2) NULL,
        [DiscountPercentage] INT NOT NULL DEFAULT 0,
        [DiscountPrice] DECIMAL(18,2) NOT NULL DEFAULT 0,
        [Unit] NVARCHAR(50) NOT NULL,
        [TotalQuantity] INT NOT NULL DEFAULT 100,
        [Description] NVARCHAR(MAX) NULL,
        [ImageUrl] NVARCHAR(500) NULL,
        [IsAvailable] BIT NOT NULL DEFAULT 1,
        [IsActive] BIT NOT NULL DEFAULT 1,
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [ModifiedDate] DATETIME2 NULL,
        CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED ([ProductId] ASC),
        CONSTRAINT [FK_Products_Categories] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Categories] ([CategoryId]) ON DELETE CASCADE
    );
END
GO

-- 3. CUSTOMERS TABLE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Customers]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[Customers] (
        [CustomerId] INT IDENTITY(1,1) NOT NULL,
        [FullName] NVARCHAR(150) NOT NULL,
        [MobileNumber] NVARCHAR(20) NOT NULL,
        [Email] NVARCHAR(150) NULL,
        [Address] NVARCHAR(MAX) NOT NULL,
        [City] NVARCHAR(100) NOT NULL,
        [Pincode] NVARCHAR(20) NOT NULL,
        [Remarks] NVARCHAR(MAX) NULL,
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [ModifiedDate] DATETIME2 NULL,
        CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED ([CustomerId] ASC)
    );
END
GO

-- 4. ORDERS TABLE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Orders]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[Orders] (
        [OrderId] INT IDENTITY(1,1) NOT NULL,
        [OrderNumber] NVARCHAR(50) NOT NULL,
        [CustomerId] INT NOT NULL,
        [OrderDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [Subtotal] DECIMAL(18,2) NOT NULL,
        [DeliveryCharge] DECIMAL(18,2) NOT NULL DEFAULT 0,
        [TotalAmount] DECIMAL(18,2) NOT NULL,
        [OrderStatus] NVARCHAR(50) NOT NULL DEFAULT 'Order Placed',
        [PaymentStatus] NVARCHAR(50) NOT NULL DEFAULT 'Pending',
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED ([OrderId] ASC),
        CONSTRAINT [FK_Orders_Customers] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customers] ([CustomerId]) ON DELETE CASCADE
    );
END
GO

-- 5. ORDER ITEMS TABLE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OrderItems]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[OrderItems] (
        [OrderItemId] INT IDENTITY(1,1) NOT NULL,
        [OrderId] INT NOT NULL,
        [ProductId] INT NOT NULL,
        [ProductName] NVARCHAR(200) NOT NULL,
        [ProductCode] NVARCHAR(50) NOT NULL,
        [Quantity] INT NOT NULL,
        [UnitPrice] DECIMAL(18,2) NOT NULL,
        [TotalPrice] DECIMAL(18,2) NOT NULL,
        CONSTRAINT [PK_OrderItems] PRIMARY KEY CLUSTERED ([OrderItemId] ASC),
        CONSTRAINT [FK_OrderItems_Orders] FOREIGN KEY ([OrderId]) REFERENCES [dbo].[Orders] ([OrderId]) ON DELETE CASCADE
    );
END
GO

-- 6. ORDER STATUS HISTORY TABLE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OrderStatusHistories]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[OrderStatusHistories] (
        [HistoryId] INT IDENTITY(1,1) NOT NULL,
        [OrderId] INT NOT NULL,
        [OldStatus] NVARCHAR(50) NULL,
        [NewStatus] NVARCHAR(50) NOT NULL,
        [ChangedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [Remarks] NVARCHAR(MAX) NULL,
        CONSTRAINT [PK_OrderStatusHistories] PRIMARY KEY CLUSTERED ([HistoryId] ASC),
        CONSTRAINT [FK_OrderStatusHistories_Orders] FOREIGN KEY ([OrderId]) REFERENCES [dbo].[Orders] ([OrderId]) ON DELETE CASCADE
    );
END
GO

-- 7. USERS TABLE (ADMIN ACCESS)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Users]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[Users] (
        [UserId] INT IDENTITY(1,1) NOT NULL,
        [Username] NVARCHAR(100) NOT NULL,
        [Email] NVARCHAR(150) NOT NULL,
        [PasswordHash] NVARCHAR(MAX) NOT NULL,
        [Role] NVARCHAR(50) NOT NULL DEFAULT 'Admin',
        [IsActive] BIT NOT NULL DEFAULT 1,
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([UserId] ASC)
    );
END
GO

-- 8. PAYMENT SETTINGS TABLE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PaymentSettings]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PaymentSettings] (
        [Id] INT IDENTITY(1,1) NOT NULL,
        [UpiId] NVARCHAR(100) NOT NULL DEFAULT '9952378965@upi',
        [UpiQrCodeUrl] NVARCHAR(300) NOT NULL DEFAULT '/assets/images/upi-qr.png',
        [CallNumber] NVARCHAR(50) NOT NULL DEFAULT '+91 6380891094',
        [AccountHolder] NVARCHAR(150) NULL,
        [BankName] NVARCHAR(150) NULL,
        [AccountNumber] NVARCHAR(100) NULL,
        [IfscCode] NVARCHAR(50) NULL,
        [UpdatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT [PK_PaymentSettings] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
END
GO

-- 9. WHATSAPP LOGS TABLE (META WHATSAPP API AUDIT TRAIL)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[WhatsAppLogs]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[WhatsAppLogs] (
        [Id] INT IDENTITY(1,1) NOT NULL,
        [OrderId] INT NOT NULL,
        [CustomerId] INT NOT NULL,
        [PhoneNumber] NVARCHAR(20) NOT NULL,
        [TemplateName] NVARCHAR(100) NOT NULL,
        [WhatsAppMessageId] NVARCHAR(100) NULL,
        [Status] NVARCHAR(50) NOT NULL DEFAULT 'PENDING',
        [ErrorMessage] NVARCHAR(MAX) NULL,
        [CreatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [SentAt] DATETIME2 NULL,
        CONSTRAINT [PK_WhatsAppLogs] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
    CREATE INDEX [IX_WhatsAppLogs_OrderId_TemplateName] ON [dbo].[WhatsAppLogs] ([OrderId], [TemplateName]);
END
GO

-- SEED PAYMENT SETTINGS
IF NOT EXISTS (SELECT 1 FROM [dbo].[PaymentSettings])
BEGIN
    INSERT INTO [dbo].[PaymentSettings] ([UpiId], [UpiQrCodeUrl], [CallNumber], [AccountHolder], [BankName], [AccountNumber], [IfscCode], [UpdatedAt])
    VALUES ('9952378965@upi', '/assets/images/upi-qr.png', '+91 6380891094', 'Karthick Crackers', 'State Bank of India', '39876543210', 'SBIN0001234', GETUTCDATE());
END
GO


-- ============================================================
-- FULL AZURE SQL SEED DATA SCRIPT (PRODUCTS, CATEGORIES, IMAGES)
-- ============================================================

SET IDENTITY_INSERT [Categories] ON;
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (1, 'Sparklers', 'Electric & Colour Sparklers', 1, '01-01-2026 00:00:00', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (2, 'Ground Chakkars', 'Spinning Wheels & Whistling Chakkars', 1, '01-01-2026 00:00:00', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (3, 'Flower Pots', 'Golden & Silver Fountains', 1, '01-01-2026 00:00:00', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (4, 'Aerial Shots', 'Multi-shot Fancy Sky Aerial Cakes', 1, '01-01-2026 00:00:00', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (5, 'Rockets', 'Sky Rockets & Lunik Bombs', 1, '01-01-2026 00:00:00', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (6, 'Kids Novelty', 'Pop-Pop, Flash Guns & Cartoons', 1, '01-01-2026 00:00:00', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (7, 'Sound Crackers', 'Bijili, Atom Bombs & Garland Crackers', 1, '01-01-2026 00:00:00', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (8, 'Gift Boxes', 'Diwali Family Assorted Gift Packs', 1, '01-01-2026 00:00:00', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (9, 'Single Sound Crackers', 'Single Sound Crackers fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (10, 'Bijili', 'Bijili fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (11, 'Chakkaram - Spinners', 'Chakkaram - Spinners fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (12, 'Kids Special', 'Kids Special fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (13, 'Color Matches', 'Color Matches fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (14, 'Bombs', 'Bombs fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (15, 'Fountain with Bomb', 'Fountain with Bomb fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (16, 'Mini Fountains', 'Mini Fountains fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (17, 'Mega Fountains', 'Mega Fountains fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (18, 'Special Fountains', 'Special Fountains fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (19, 'Fancy Novelties', 'Fancy Novelties fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (20, 'Sky Shots', 'Sky Shots fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (21, 'Ariel Shots Continuous Functions', 'Ariel Shots Continuous Functions fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (22, 'Rider Shots', 'Rider Shots fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (23, 'Musical Shots', 'Musical Shots fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (24, 'Special Function Shots', 'Special Function Shots fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (25, 'Sparkers', 'Sparkers fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (26, '2026 Special', '2026 Special fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
INSERT INTO [Categories] ([CategoryId], [CategoryName], [Description], [IsActive], [CreatedDate], [ModifiedDate]) VALUES (27, 'Festival Crackers', 'Festival Crackers fireworks collection.', 1, '09-09-2026 18:07:04', NULL);
SET IDENTITY_INSERT [Categories] OFF;
GO

SET IDENTITY_INSERT [Products] ON;
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (1, '1', '2 3/4'' Kuruvi', 9, 'Premium Sivakasi 2 3/4'' Kuruvi. Quality safety checked.', 8.10, '1 Box', 'assets/productimg/KHC-1001.jpg', 1, 1, '11-09-2026 11:52:21', '11-09-2026 18:12:22', 18.00, 55.00, 8.10, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (2, '2', '3 1/2'' Lakshmi', 9, 'Premium Sivakasi 3 1/2'' Lakshmi. Quality safety checked.', 13.50, '1 Box', 'assets/productimg/KHC-1002.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 30.00, 55.00, 13.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (3, '3', '4'' Lakshmi', 9, 'Premium Sivakasi 4'' Lakshmi. Quality safety checked.', 18.90, '1 Box', 'assets/productimg/KHC-1003.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 42.00, 55.00, 18.90, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (4, '4', '4'' Dlx Lakshmi', 9, 'Premium Sivakasi 4'' Dlx Lakshmi. Quality safety checked.', 32.40, '1 Box', 'assets/productimg/KHC-1004.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 72.00, 55.00, 32.40, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (5, '5', 'Gold Lakshmi', 9, 'Premium Sivakasi Gold Lakshmi. Quality safety checked.', 34.20, '1 Box', 'assets/productimg/KHC-1005.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 76.00, 55.00, 34.20, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (6, '6', '5'' Mega Lakshmi', 9, 'Premium Sivakasi 5'' Mega Lakshmi. Quality safety checked.', 54.00, '1 Box', 'assets/productimg/KHC-1006.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 120.00, 55.00, 54.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (7, '7', '6'' Mega Lakshmi', 9, 'Premium Sivakasi 6'' Mega Lakshmi. Quality safety checked.', 67.50, '1 Box', 'assets/productimg/KHC-1007.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 150.00, 55.00, 67.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (8, '8', 'Two Sound', 9, 'Premium Sivakasi Two Sound. Quality safety checked.', 34.20, '1 Box', 'assets/productimg/KHC-1008.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 76.00, 55.00, 34.20, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (9, '9', 'Red/ Striped Bijili (100 Pcs)', 10, 'Premium Sivakasi Red/ Striped Bijili (100 Pcs). Quality safety checked.', 32.40, '1 Box', 'assets/productimg/KHC-1009.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 72.00, 55.00, 32.40, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (10, '10', 'Ground Chakkar Big', 11, 'Premium Sivakasi Ground Chakkar Big. Quality safety checked.', 36.00, '1 Box', 'assets/productimg/KHC-1010.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 80.00, 55.00, 36.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (11, '11', 'Ground Chakkar Special', 11, 'Premium Sivakasi Ground Chakkar Special. Quality safety checked.', 66.60, '1 Box', 'assets/productimg/KHC-1011.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 148.00, 55.00, 66.60, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (12, '12', 'Ground Chakkar Deluxe', 11, 'Premium Sivakasi Ground Chakkar Deluxe. Quality safety checked.', 112.50, '1 Box', 'assets/productimg/KHC-1012.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 250.00, 55.00, 112.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (13, '13', 'Wire Chakkarm', 11, 'Premium Sivakasi Wire Chakkarm. Quality safety checked.', 162.00, '1 Box', 'assets/productimg/KHC-1013.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 360.00, 55.00, 162.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (14, '14', 'Whistling wheel', 11, 'Premium Sivakasi Whistling wheel. Quality safety checked.', 117.00, '1 Box', 'assets/productimg/KHC-1014.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 260.00, 55.00, 117.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (15, '15', 'Disco Wheel', 11, 'Premium Sivakasi Disco Wheel. Quality safety checked.', 94.50, '1 Box', 'assets/productimg/KHC-1015.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 210.00, 55.00, 94.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (16, '16', '4 x 4 Wheel', 11, 'Premium Sivakasi 4 x 4 Wheel. Quality safety checked.', 153.00, '1 Box', 'assets/productimg/KHC-1016.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 340.00, 55.00, 153.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (17, '17', 'Flower Pots Big', 3, 'Premium Sivakasi Flower Pots Big. Quality safety checked.', 67.50, '1 Box', 'assets/productimg/KHC-1017.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 150.00, 55.00, 67.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (18, '18', 'Flower Pots Special', 3, 'Premium Sivakasi Flower Pots Special. Quality safety checked.', 83.70, '1 Box', 'assets/productimg/KHC-1018.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 186.00, 55.00, 83.70, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (19, '19', 'Flower Pots Asoka', 3, 'Premium Sivakasi Flower Pots Asoka. Quality safety checked.', 103.50, '1 Box', 'assets/productimg/KHC-1019.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 230.00, 55.00, 103.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (20, '20', 'Colour Koti', 3, 'Premium Sivakasi Colour Koti. Quality safety checked.', 175.50, '1 Box', 'assets/productimg/KHC-1020.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 390.00, 55.00, 175.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (21, '21', 'Rangeela Colour Koti', 3, 'Premium Sivakasi Rangeela Colour Koti. Quality safety checked.', 243.00, '1 Box', 'assets/productimg/KHC-1021.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 540.00, 55.00, 243.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (22, '22', 'Colour Koti Deluxe', 3, 'Premium Sivakasi Colour Koti Deluxe. Quality safety checked.', 315.00, '1 Box', 'assets/productimg/KHC-1022.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 700.00, 55.00, 315.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (23, '23', 'Flower Pot Deluxe (5 Pcs)', 3, 'Premium Sivakasi Flower Pot Deluxe (5 Pcs). Quality safety checked.', 157.50, '1 Box', 'assets/productimg/KHC-1023.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 350.00, 55.00, 157.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (24, '24', 'Flower Pot Super Deluxe (2 Pcs)', 3, 'Premium Sivakasi Flower Pot Super Deluxe (2 Pcs). Quality safety checked.', 112.50, '1 Box', 'assets/productimg/KHC-1024.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 250.00, 55.00, 112.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (25, '25', 'Tri Colour (5 Pcs )', 3, 'Premium Sivakasi Tri Colour (5 Pcs ). Quality safety checked.', 261.00, '1 Box', 'assets/productimg/KHC-1025.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 580.00, 55.00, 261.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (26, '26', '1 1/2 Twinkling Star', 12, 'Premium Sivakasi 1 1/2 Twinkling Star. Quality safety checked.', 27.00, '1 Box', 'assets/productimg/KHC-1026.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 60.00, 55.00, 27.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (27, '27', '4'' Twinkling Star', 12, 'Premium Sivakasi 4'' Twinkling Star. Quality safety checked.', 67.50, '1 Box', 'assets/productimg/KHC-1027.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 150.00, 55.00, 67.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (28, '28', 'Electric Stone', 12, 'Premium Sivakasi Electric Stone. Quality safety checked.', 9.00, '1 Box', 'assets/productimg/KHC-1028.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 20.00, 55.00, 9.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (29, '29', 'Kit Kat', 12, 'Premium Sivakasi Kit Kat. Quality safety checked.', 31.50, '1 Box', 'assets/productimg/KHC-1029.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 70.00, 55.00, 31.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (30, '30', 'Serphant Egg', 12, 'Premium Sivakasi Serphant Egg. Quality safety checked.', 36.00, '1 Box', 'assets/productimg/KHC-1030.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 80.00, 55.00, 36.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (31, '31', 'Top Gun (5 Pcs)', 12, 'Premium Sivakasi Top Gun (5 Pcs). Quality safety checked.', 202.50, '1 Box', 'assets/productimg/KHC-1031.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 450.00, 55.00, 202.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (32, '32', '5G Free Fire Gun (2 Pcs)', 12, 'Premium Sivakasi 5G Free Fire Gun (2 Pcs). Quality safety checked.', 238.50, '1 Box', '/assets/images/5g-free-fire-gun.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 530.00, 55.00, 238.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (33, '33', 'Jackpot Currency', 12, 'Premium Sivakasi Jackpot Currency. Quality safety checked.', 225.00, '1 Box', '/assets/images/jackpot-currency.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 500.00, 55.00, 225.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (34, '34', 'Bambaram', 12, 'Premium Sivakasi Bambaram. Quality safety checked.', 99.00, '1 Box', 'assets/productimg/KHC-1034.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 220.00, 55.00, 99.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (35, '35', 'Money in the Bank', 12, 'Premium Sivakasi Money in the Bank. Quality safety checked.', 54.00, '1 Box', 'assets/productimg/KHC-1035.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 120.00, 55.00, 54.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (36, '36', 'Lamba', 13, 'Premium Sivakasi Lamba. Quality safety checked.', 135.00, '1 Box', 'assets/productimg/KHC-1036.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 300.00, 55.00, 135.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (37, '37', 'Laptop', 13, 'Premium Sivakasi Laptop. Quality safety checked.', 225.00, '1 Box', 'assets/productimg/KHC-1037.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 500.00, 55.00, 225.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (38, '38', 'Hydro Bomb', 14, 'Premium Sivakasi Hydro Bomb. Quality safety checked.', 76.50, '1 Box', 'assets/productimg/KHC-1038.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 170.00, 55.00, 76.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (39, '39', 'King of King', 14, 'Premium Sivakasi King of King. Quality safety checked.', 94.50, '1 Box', 'assets/productimg/KHC-1039.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 210.00, 55.00, 94.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (40, '40', 'Classic Bomb', 14, 'Premium Sivakasi Classic Bomb. Quality safety checked.', 112.50, '1 Box', 'assets/productimg/KHC-1040.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 250.00, 55.00, 112.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (41, '41', 'Agni Bomb', 14, 'Premium Sivakasi Agni Bomb. Quality safety checked.', 224.10, '1 Box', 'assets/productimg/KHC-1041.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 498.00, 55.00, 224.10, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (42, '42', 'Circar Bomb Big', 14, 'Premium Sivakasi Circar Bomb Big. Quality safety checked.', 283.50, '1 Box', 'assets/productimg/KHC-1042.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 630.00, 55.00, 283.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (43, '43', 'Paper Bomb (1/4 Kg)', 14, 'Premium Sivakasi Paper Bomb (1/4 Kg). Quality safety checked.', 54.00, '1 Box', 'assets/productimg/KHC-1043.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 120.00, 55.00, 54.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (44, '44', 'Paper Bomb (1/2 Kg)', 14, 'Premium Sivakasi Paper Bomb (1/2 Kg). Quality safety checked.', 108.00, '1 Box', 'assets/productimg/KHC-1044.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 240.00, 55.00, 108.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (45, '45', 'Paper Bomb (1 Kg)', 14, 'Premium Sivakasi Paper Bomb (1 Kg). Quality safety checked.', 216.00, '1 Box', 'assets/productimg/KHC-1045.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 480.00, 55.00, 216.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (46, '46', 'Ganga Yamuna', 15, 'Premium Sivakasi Ganga Yamuna. Quality safety checked.', 135.00, '1 Box', 'assets/productimg/KHC-1046.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 300.00, 55.00, 135.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (47, '47', 'Rocket Bomb', 5, 'Premium Sivakasi Rocket Bomb. Quality safety checked.', 67.50, '1 Box', 'assets/productimg/KHC-1047.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 150.00, 55.00, 67.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (48, '48', 'Mega Rocket', 5, 'Premium Sivakasi Mega Rocket. Quality safety checked.', 117.00, '1 Box', 'assets/productimg/KHC-1048.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 260.00, 55.00, 117.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (49, '49', 'Whisling Rocket', 5, 'Premium Sivakasi Whisling Rocket. Quality safety checked.', 175.50, '1 Box', 'assets/productimg/KHC-1049.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 390.00, 55.00, 175.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (50, '50', 'Peacock Feather', 16, 'Premium Sivakasi Peacock Feather. Quality safety checked.', 97.20, '1 Box', 'assets/productimg/KHC-1050.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 216.00, 55.00, 97.20, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (51, '51', 'Color Rain', 16, 'Premium Sivakasi Color Rain. Quality safety checked.', 97.20, '1 Box', 'assets/productimg/KHC-1051.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 216.00, 55.00, 97.20, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (52, '52', 'Golden Globe', 16, 'Premium Sivakasi Golden Globe. Quality safety checked.', 97.20, '1 Box', 'assets/productimg/KHC-1052.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 216.00, 55.00, 97.20, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (53, '53', 'Sun Lights', 16, 'Premium Sivakasi Sun Lights. Quality safety checked.', 97.20, '1 Box', 'assets/productimg/KHC-1053.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 216.00, 55.00, 97.20, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (54, '54', 'Moon Lights', 16, 'Premium Sivakasi Moon Lights. Quality safety checked.', 97.20, '1 Box', 'assets/productimg/KHC-1054.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 216.00, 55.00, 97.20, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (55, '55', 'Siren (3 Pcs)', 17, 'Premium Sivakasi Siren (3 Pcs). Quality safety checked.', 171.00, '1 Box', 'assets/productimg/KHC-1055.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 380.00, 55.00, 171.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (56, '56', 'Cocktail (2 Pcs)', 17, 'Premium Sivakasi Cocktail (2 Pcs). Quality safety checked.', 180.00, '1 Box', 'assets/productimg/KHC-1056.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 400.00, 55.00, 180.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (57, '57', 'Magical Peacock', 17, 'Premium Sivakasi Magical Peacock. Quality safety checked.', 135.00, '1 Box', 'assets/productimg/KHC-1057.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 300.00, 55.00, 135.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (58, '58', 'Bada Peacock', 17, 'Premium Sivakasi Bada Peacock. Quality safety checked.', 396.00, '1 Box', 'assets/productimg/KHC-1058.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 880.00, 55.00, 396.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (59, '59', 'Tin Beer', 17, 'Premium Sivakasi Tin Beer. Quality safety checked.', 108.00, '1 Box', 'assets/productimg/KHC-1059.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 240.00, 55.00, 108.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (60, '60', '2 Step Fountain', 17, 'Premium Sivakasi 2 Step Fountain. Quality safety checked.', 139.50, '1 Box', 'assets/productimg/KHC-1060.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 310.00, 55.00, 139.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (61, '61', 'Tuskar (2 Pcs)', 17, 'Premium Sivakasi Tuskar (2 Pcs). Quality safety checked.', 265.50, '1 Box', 'assets/productimg/KHC-1061.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 590.00, 55.00, 265.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (62, '62', 'Kicker ZZZ', 17, 'Premium Sivakasi Kicker ZZZ. Quality safety checked.', 108.00, '1 Box', 'assets/productimg/KHC-1062.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 240.00, 55.00, 108.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (63, '63', 'Water Queen', 17, 'Premium Sivakasi Water Queen. Quality safety checked.', 171.00, '1 Box', 'assets/productimg/KHC-1063.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 380.00, 55.00, 171.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (64, '64', 'Bingepop (Popcorn)', 17, 'Premium Sivakasi Bingepop (Popcorn). Quality safety checked.', 135.00, '1 Box', 'assets/productimg/KHC-1064.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 300.00, 55.00, 135.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (65, '65', 'Jumbo Tin', 17, 'Premium Sivakasi Jumbo Tin. Quality safety checked.', 189.00, '1 Box', 'assets/productimg/KHC-1065.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 420.00, 55.00, 189.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (66, '66', 'Purpee Bees (Violet)', 18, 'Premium Sivakasi Purpee Bees (Violet). Quality safety checked.', 216.00, '1 Box', 'assets/productimg/KHC-1066.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 480.00, 55.00, 216.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (67, '67', 'Barbie (Pink)', 18, 'Premium Sivakasi Barbie (Pink). Quality safety checked.', 216.00, '1 Box', 'assets/productimg/KHC-1067.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 480.00, 55.00, 216.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (68, '68', 'Ocean Blue (Blue)', 18, 'Premium Sivakasi Ocean Blue (Blue). Quality safety checked.', 216.00, '1 Box', 'assets/productimg/KHC-1068.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 480.00, 55.00, 216.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (69, '69', 'Drone', 19, 'Premium Sivakasi Drone. Quality safety checked.', 135.00, '1 Box', 'assets/productimg/KHC-1069.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 300.00, 55.00, 135.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (70, '70', 'Helicopter', 19, 'Premium Sivakasi Helicopter. Quality safety checked.', 85.50, '1 Box', 'assets/productimg/KHC-1070.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 190.00, 55.00, 85.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (71, '71', 'Gems Color Mix', 19, 'Premium Sivakasi Gems Color Mix. Quality safety checked.', 171.00, '1 Box', 'assets/productimg/KHC-1071.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 380.00, 55.00, 171.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (72, '72', 'Rainbow Smoke', 19, 'Premium Sivakasi Rainbow Smoke. Quality safety checked.', 135.00, '1 Box', 'assets/productimg/KHC-1072.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 300.00, 55.00, 135.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (73, '73', 'Butterfly', 19, 'Premium Sivakasi Butterfly. Quality safety checked.', 90.00, '1 Box', 'assets/productimg/KHC-1073.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 200.00, 55.00, 90.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (74, '74', 'Photo Flash', 19, 'Premium Sivakasi Photo Flash. Quality safety checked.', 72.00, '1 Box', 'assets/productimg/KHC-1074.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 160.00, 55.00, 72.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (75, '75', 'Selfie Stick', 19, 'Premium Sivakasi Selfie Stick. Quality safety checked.', 135.00, '1 Box', 'assets/productimg/KHC-1075.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 300.00, 55.00, 135.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (76, '76', 'Sizzle Rain', 19, 'Premium Sivakasi Sizzle Rain. Quality safety checked.', 162.00, '1 Box', 'assets/productimg/KHC-1076.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 360.00, 55.00, 162.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (77, '77', 'Lolli Pop', 19, 'Premium Sivakasi Lolli Pop. Quality safety checked.', 234.00, '1 Box', 'assets/productimg/KHC-1077.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 520.00, 55.00, 234.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (78, '78', 'Chotta Fancy', 20, 'Premium Sivakasi Chotta Fancy. Quality safety checked.', 40.50, '1 Box', 'assets/productimg/KHC-1078.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 90.00, 55.00, 40.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (79, '79', '7 Shot', 20, 'Premium Sivakasi 7 Shot. Quality safety checked.', 82.80, '1 Box', 'assets/productimg/KHC-1079.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 184.00, 55.00, 82.80, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (80, '80', '2'' Fancy', 20, 'Premium Sivakasi 2'' Fancy. Quality safety checked.', 90.00, '1 Box', 'assets/productimg/KHC-1080.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 200.00, 55.00, 90.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (81, '81', '3 Pcs Fancy', 20, 'Premium Sivakasi 3 Pcs Fancy. Quality safety checked.', 238.50, '1 Box', 'assets/productimg/KHC-1081.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 530.00, 55.00, 238.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (82, '82', '3 1/2'' Fancy', 20, 'Premium Sivakasi 3 1/2'' Fancy. Quality safety checked.', 265.50, '1 Box', 'assets/productimg/KHC-1082.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 590.00, 55.00, 265.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (83, '83', '3 1/2'' Nayagara Falls', 20, 'Premium Sivakasi 3 1/2'' Nayagara Falls. Quality safety checked.', 306.00, '1 Box', 'assets/productimg/KHC-1083.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 680.00, 55.00, 306.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (84, '84', '4'' Fancy', 20, 'Premium Sivakasi 4'' Fancy. Quality safety checked.', 360.00, '1 Box', 'assets/productimg/KHC-1084.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 800.00, 55.00, 360.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (85, '85', '4'' Twelve Step', 20, 'Premium Sivakasi 4'' Twelve Step. Quality safety checked.', 387.00, '1 Box', 'assets/productimg/KHC-1085.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 860.00, 55.00, 387.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (86, '86', '4'' Blue '' Pink', 20, 'Premium Sivakasi 4'' Blue '' Pink. Quality safety checked.', 450.00, '1 Box', 'assets/productimg/KHC-1086.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 1000.00, 55.00, 450.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (87, '87', '4'' Double Ball', 20, 'Premium Sivakasi 4'' Double Ball. Quality safety checked.', 450.00, '1 Box', 'assets/productimg/KHC-1087.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 1000.00, 55.00, 450.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (88, '88', '12 Shots', 21, 'Premium Sivakasi 12 Shots. Quality safety checked.', 162.00, '1 Box', 'assets/productimg/KHC-1088.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 360.00, 55.00, 162.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (89, '89', '15 Shots', 21, 'Premium Sivakasi 15 Shots. Quality safety checked.', 292.50, '1 Box', 'assets/productimg/KHC-1089.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 650.00, 55.00, 292.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (90, '90', '30 Shots', 21, 'Premium Sivakasi 30 Shots. Quality safety checked.', 432.00, '1 Box', 'assets/productimg/KHC-1090.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 960.00, 55.00, 432.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (91, '91', '60 Shots', 21, 'Premium Sivakasi 60 Shots. Quality safety checked.', 864.00, '1 Box', 'assets/productimg/KHC-1091.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 1920.00, 55.00, 864.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (92, '92', '120 Shots', 21, 'Premium Sivakasi 120 Shots. Quality safety checked.', 1728.00, '1 Box', 'assets/productimg/KHC-1092.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 3840.00, 55.00, 1728.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (93, '93', '240 Shots', 21, 'Premium Sivakasi 240 Shots. Quality safety checked.', 3456.00, '1 Box', 'assets/productimg/KHC-1093.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 7680.00, 55.00, 3456.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (94, '94', '25 Shots rider', 22, 'Premium Sivakasi 25 Shots rider. Quality safety checked.', 234.00, '1 Box', 'assets/productimg/KHC-1094.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 520.00, 55.00, 234.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (95, '95', '50 Shots rider', 22, 'Premium Sivakasi 50 Shots rider. Quality safety checked.', 468.00, '1 Box', 'assets/productimg/KHC-1095.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 1040.00, 55.00, 468.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (96, '96', '10 shots singing dolls', 23, 'Premium Sivakasi 10 shots singing dolls. Quality safety checked.', 315.00, '1 Box', 'assets/productimg/KHC-1096.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 700.00, 55.00, 315.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (97, '97', 'Music zip 25 Shots', 23, 'Premium Sivakasi Music zip 25 Shots. Quality safety checked.', 855.00, '1 Box', 'assets/productimg/KHC-1097.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 1900.00, 55.00, 855.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (98, '98', 'Festival Slice 50 Shots', 23, 'Premium Sivakasi Festival Slice 50 Shots. Quality safety checked.', 1350.00, '1 Box', 'assets/productimg/KHC-1098.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 3000.00, 55.00, 1350.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (99, '99', '5 x 10 Holi Celebration', 24, 'Premium Sivakasi 5 x 10 Holi Celebration. Quality safety checked.', 2430.00, '1 Box', 'assets/productimg/KHC-1099.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 5400.00, 55.00, 2430.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (100, '100', '10 x 10 Tail Light', 24, 'Premium Sivakasi 10 x 10 Tail Light. Quality safety checked.', 4320.00, '1 Box', 'assets/productimg/KHC-1100.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 9600.00, 55.00, 4320.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (101, '101', 'Akash Mela Celebration', 24, 'Premium Sivakasi Akash Mela Celebration. Quality safety checked.', 4140.00, '1 Box', 'assets/productimg/KHC-1101.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 9200.00, 55.00, 4140.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (102, '102', 'Dasara Celebration', 24, 'Premium Sivakasi Dasara Celebration. Quality safety checked.', 4320.00, '1 Box', 'assets/productimg/KHC-1102.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 9600.00, 55.00, 4320.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (103, '103', '10 Cm Electric Sparklers', 25, 'Premium Sivakasi 10 Cm Electric Sparklers. Quality safety checked.', 18.00, '1 Box', 'assets/productimg/KHC-1103.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 40.00, 55.00, 18.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (104, '104', '10 CM Colour Sparklers', 25, 'Premium Sivakasi 10 CM Colour Sparklers. Quality safety checked.', 19.80, '1 Box', 'assets/productimg/KHC-1104.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 44.00, 55.00, 19.80, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (105, '105', '10 CM Green Sparklers', 25, 'Premium Sivakasi 10 CM Green Sparklers. Quality safety checked.', 21.60, '1 Box', 'assets/productimg/KHC-1105.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 48.00, 55.00, 21.60, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (106, '106', '10 CM Red Sparklers', 25, 'Premium Sivakasi 10 CM Red Sparklers. Quality safety checked.', 23.40, '1 Box', 'assets/productimg/KHC-1106.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 52.00, 55.00, 23.40, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (107, '107', '15 CM Electric Sparklers', 25, 'Premium Sivakasi 15 CM Electric Sparklers. Quality safety checked.', 37.80, '1 Box', 'assets/productimg/KHC-1107.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 84.00, 55.00, 37.80, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (108, '108', '15 CM Colour Sparklers', 25, 'Premium Sivakasi 15 CM Colour Sparklers. Quality safety checked.', 39.60, '1 Box', 'assets/productimg/KHC-1108.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 88.00, 55.00, 39.60, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (109, '109', '15 CM Green Sparklers', 25, 'Premium Sivakasi 15 CM Green Sparklers. Quality safety checked.', 43.20, '1 Box', 'assets/productimg/KHC-1109.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 96.00, 55.00, 43.20, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (110, '110', '15 CM Red Sparklers', 25, 'Premium Sivakasi 15 CM Red Sparklers. Quality safety checked.', 45.00, '1 Box', 'assets/productimg/KHC-1110.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 100.00, 55.00, 45.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (111, '111', '30 CM Electric Sparklers', 25, 'Premium Sivakasi 30 CM Electric Sparklers. Quality safety checked.', 37.80, '1 Box', 'assets/productimg/KHC-1111.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 84.00, 55.00, 37.80, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (112, '112', '30 CM Colour Sparklers', 25, 'Premium Sivakasi 30 CM Colour Sparklers. Quality safety checked.', 39.60, '1 Box', 'assets/productimg/KHC-1112.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 88.00, 55.00, 39.60, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (113, '113', '30 CM Green Sparklers', 25, 'Premium Sivakasi 30 CM Green Sparklers. Quality safety checked.', 43.20, '1 Box', 'assets/productimg/KHC-1113.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 96.00, 55.00, 43.20, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (114, '114', '30 CM Red Sparklers', 25, 'Premium Sivakasi 30 CM Red Sparklers. Quality safety checked.', 45.00, '1 Box', 'assets/productimg/KHC-1114.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 100.00, 55.00, 45.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (115, '115', '50 CM Electric Sparklers', 25, 'Premium Sivakasi 50 CM Electric Sparklers. Quality safety checked.', 153.00, '1 Box', 'assets/productimg/KHC-1115.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 340.00, 55.00, 153.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (116, '116', '50 CM Colour Sparklers', 25, 'Premium Sivakasi 50 CM Colour Sparklers. Quality safety checked.', 171.00, '1 Box', 'assets/productimg/KHC-1116.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 380.00, 55.00, 171.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (117, '117', 'Fruit series Fountation', 26, 'Premium Sivakasi Fruit series Fountation. Quality safety checked.', 180.00, '1 Box', 'assets/productimg/KHC-1117.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 400.00, 55.00, 180.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (118, '118', 'Jungle Series Fountation', 26, 'Premium Sivakasi Jungle Series Fountation. Quality safety checked.', 189.00, '1 Box', 'assets/productimg/KHC-1118.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 420.00, 55.00, 189.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (119, '119', 'Fire Egg', 26, 'Premium Sivakasi Fire Egg. Quality safety checked.', 171.00, '1 Box', 'assets/productimg/KHC-1119.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 380.00, 55.00, 171.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (120, '120', 'Mushroom', 26, 'Premium Sivakasi Mushroom. Quality safety checked.', 148.50, '1 Box', 'assets/productimg/KHC-1120.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 330.00, 55.00, 148.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (121, '121', 'Smoke Cylinder Bomb', 26, 'Premium Sivakasi Smoke Cylinder Bomb. Quality safety checked.', 265.50, '1 Box', 'assets/productimg/KHC-1121.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 590.00, 55.00, 265.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (122, '122', 'Funky Fish', 26, 'Premium Sivakasi Funky Fish. Quality safety checked.', 207.00, '1 Box', 'assets/productimg/KHC-1122.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 460.00, 55.00, 207.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (123, '123', 'Soora Samkaaram', 26, 'Premium Sivakasi Soora Samkaaram. Quality safety checked.', 324.00, '1 Box', 'assets/productimg/KHC-1123.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 720.00, 55.00, 324.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (124, '124', 'Watter Melon ( 2 Pcs)', 26, 'Premium Sivakasi Watter Melon ( 2 Pcs). Quality safety checked.', 279.00, '1 Box', 'assets/productimg/KHC-1124.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 620.00, 55.00, 279.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (125, '125', '100 Wala', 27, 'Premium Sivakasi 100 Wala. Quality safety checked.', 40.50, '1 Box', 'assets/productimg/KHC-1125.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 90.00, 55.00, 40.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (126, '126', '28 Giant', 27, 'Premium Sivakasi 28 Giant. Quality safety checked.', 27.00, '1 Box', 'assets/productimg/KHC-1126.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 60.00, 55.00, 27.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (127, '127', '56 Giant', 27, 'Premium Sivakasi 56 Giant. Quality safety checked.', 54.00, '1 Box', 'assets/productimg/KHC-1127.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 120.00, 55.00, 54.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (128, '128', '24 Deluxe', 27, 'Premium Sivakasi 24 Deluxe. Quality safety checked.', 63.00, '1 Box', 'assets/productimg/KHC-1128.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 140.00, 55.00, 63.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (129, '129', '50 Deluxe', 27, 'Premium Sivakasi 50 Deluxe. Quality safety checked.', 112.50, '1 Box', 'assets/productimg/KHC-1129.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 250.00, 55.00, 112.50, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (130, '130', '100 Deluxe', 27, 'Premium Sivakasi 100 Deluxe. Quality safety checked.', 225.00, '1 Box', 'assets/productimg/KHC-1130.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 500.00, 55.00, 225.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (131, '131', '1000 Wala power', 27, 'Premium Sivakasi 1000 Wala power. Quality safety checked.', 270.00, '1 Box', 'assets/productimg/KHC-1131.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 600.00, 55.00, 270.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (132, '132', '2000 Wala power', 27, 'Premium Sivakasi 2000 Wala power. Quality safety checked.', 540.00, '1 Box', 'assets/productimg/KHC-1132.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 1200.00, 55.00, 540.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (133, '133', '5000 Wala power', 27, 'Premium Sivakasi 5000 Wala power. Quality safety checked.', 1350.00, '1 Box', 'assets/productimg/KHC-1133.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 3000.00, 55.00, 1350.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (134, '134', '10000 Wala power', 27, 'Premium Sivakasi 10000 Wala power. Quality safety checked.', 2700.00, '1 Box', 'assets/productimg/KHC-1134.jpg', 1, 1, '11-09-2026 11:52:21', NULL, 6000.00, 55.00, 2700.00, 50);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (308, '308', 'Zumba Dance', 8, 'Premium Diwali Gift Box with 12 Items', 236.00, '1 Box (12 Items)', '/assets/images/family-giftbox.jpg', 1, 1, '18-09-2026 13:33:35', NULL, 524.44, 55.00, 236.00, 60);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (309, '309', 'Super Star', 8, 'Premium Diwali Gift Box with 18 Items', 320.00, '1 Box (18 Items)', '/assets/images/family-giftbox.jpg', 1, 1, '18-09-2026 13:33:35', NULL, 711.11, 55.00, 320.00, 45);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (310, '310', 'Peacock Dance-UV', 8, 'Premium Diwali Gift Box with 21 Items', 395.00, '1 Box (21 Items)', '/assets/images/family-giftbox.jpg', 1, 1, '18-09-2026 13:33:35', NULL, 877.78, 55.00, 395.00, 38);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (311, '311', 'Samba Party', 8, 'Premium Diwali Gift Box with 24 Items', 470.00, '1 Box (24 Items)', '/assets/images/family-giftbox.jpg', 1, 1, '18-09-2026 13:33:35', NULL, 1044.44, 55.00, 470.00, 32);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (312, '312', 'Kuchipudi Dance', 8, 'Premium Diwali Gift Box with 30 Items', 590.00, '1 Box (30 Items)', '/assets/images/family-giftbox.jpg', 1, 1, '18-09-2026 13:33:35', NULL, 1311.11, 55.00, 590.00, 26);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (313, '313', 'Rhythums', 8, 'Premium Diwali Gift Box with 36 Items', 850.00, '1 Box (36 Items)', '/assets/images/family-giftbox.jpg', 1, 1, '18-09-2026 13:33:35', NULL, 1888.89, 55.00, 850.00, 20);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (314, '314', 'Belley Dance-UV', 8, 'Premium Diwali Gift Box with 42 Items', 970.00, '1 Box (42 Items)', '/assets/images/family-giftbox.jpg', 1, 1, '18-09-2026 13:33:35', NULL, 2155.56, 55.00, 970.00, 18);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (315, '315', 'Kaithakali Dance-UV', 8, 'Premium Diwali Gift Box with 51 Items', 1240.00, '1 Box (51 Items)', '/assets/images/family-giftbox.jpg', 1, 1, '18-09-2026 13:33:35', NULL, 2755.56, 55.00, 1240.00, 12);
INSERT INTO [Products] ([ProductId], [ProductCode], [ProductName], [CategoryId], [Description], [Price], [Unit], [ImageUrl], [IsAvailable], [IsActive], [CreatedDate], [ModifiedDate], [MRPPrice], [DiscountPercentage], [DiscountPrice], [TotalQuantity]) VALUES (316, '316', 'Dragon Dance-UV', 8, 'Premium Diwali Gift Box with 60 Items', 1600.00, '1 Box (60 Items)', '/assets/images/family-giftbox.jpg', 1, 1, '18-09-2026 13:33:35', NULL, 3555.56, 55.00, 1600.00, 8);
SET IDENTITY_INSERT [Products] OFF;
GO

SET IDENTITY_INSERT [PaymentSettings] ON;
INSERT INTO [PaymentSettings] ([Id], [UpiId], [UpiQrCodeUrl], [CallNumber], [AccountHolder], [BankName], [AccountNumber], [IfscCode], [UpdatedAt]) VALUES (1, '9952378965@upi', '/uploads/settings/upi-qr-639251691775862626.png', '+91 6380891094', NULL, NULL, NULL, NULL, '16-09-2026 15:26:17');
SET IDENTITY_INSERT [PaymentSettings] OFF;
GO

SET IDENTITY_INSERT [Users] ON;
INSERT INTO [Users] ([UserId], [Email], [PasswordHash], [Role], [IsActive], [CreatedDate], [ModifiedDate], [MobileNumber]) VALUES (1, 'karthickkumar2014000@gmail.com', 'AQAAAAIAAYagAAAAEJ1yvQtPnWFCyoLssKLP0jgZIXzrnH6qKqW4V33j8Z2SzmPddSVMK6illKtowBzVMA==', 'Admin', 1, '01-01-2026 00:00:00', NULL, '7010616198');
SET IDENTITY_INSERT [Users] OFF;
GO


